### ISSUE TITLE
ItemForm displays a line of code on an empty text field.

### ISSUE THREAD

**Issue by ReconFlux** [datta-register/dattatable#25]
![image](https://user-images.githubusercontent.com/24204923/182739321-f2c7352f-b402-4c10-a2aa-87af10b4229e.png)

Steps to reproduce.

1. create a field in the .cfg = `type: Helper.SPCfgFieldType.Text,`
2. Render the ItemForm by an onclick event:
`onClick: () => {
 // Create an item
 ItemForm.create({`

3. Leave the field blank and click update.
4.  Render the ItemForm.Display or Item.Edit.

If you edit the field and update it, you get error 500 and the solution hangs.

![image](https://user-images.githubusercontent.com/24204923/182739813-73ffcc24-23ec-4bd9-b34c-5b70e49b31d8.png)

![image](https://user-images.githubusercontent.com/24204923/182739792-ffafa218-0387-41c7-9bcc-556743c08f0e.png)

**Comment by gunjandatta** [comment]
We have added a rich textbox feature, that may help this out. I'm not sure if this is still an issue or not, as we haven't been able to recreate this issue.
