### ISSUE TITLE
Update ListSecurityDefaultGroups to show the actual Associated group name

### ISSUE THREAD

**Issue by Dade-R** [datta-register/dattatable#32]
When using ListSecurityDefaultGroups.Owners, the GroupName is shown as 'owners'. This should render as the real AssociatedOwners group name from the site.

Please update all 3 associated groups to use the real group name in the UI.

visitor --> $Site Visitors
member --> $Site Members
owner --> $Site Owners

**Comment by gunjandatta** [comment]
Fixed in v2.9.23.
